import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.about': 'Présentation',
    'nav.services': 'Services',
    'nav.laboratory': 'Laboratoire',
    'nav.training': 'Formations',
    'nav.contact': 'Contact',

    // Hero Section
    'hero.title': 'Expertise Technique & Formation aux Métiers',
    'hero.subtitle': 'Excellence, Innovation et Professionnalisme au service de votre développement',
    'hero.cta': 'Découvrir nos services',

    // About
    'about.title': 'À propos d\'EXFORM',
    'about.subtitle': 'Notre mission, nos valeurs, notre vision',
    'about.badge': 'À Propos d\'EXFORM',
    'about.story.badge': 'Notre Parcours',
    'about.story.title': 'Notre Histoire',
    'about.story.paragraph1': 'Fondée avec la vision de transformer le paysage de la formation technique et de l\'expertise industrielle en Côte d\'Ivoire, EXFORM s\'est rapidement imposée comme un acteur incontournable du secteur.',
    'about.story.paragraph2': 'Depuis nos débuts, nous avons formé plus de 500 professionnels et accompagné des centaines d\'entreprises dans leur développement. Notre laboratoire d\'analyse physico-chimique est reconnu pour sa précision et sa conformité aux normes internationales.',
    'about.story.paragraph3': 'Aujourd\'hui, EXFORM continue d\'évoluer pour répondre aux défis technologiques et industriels de demain, tout en maintenant notre engagement envers l\'excellence et l\'innovation.',
    'about.stats.experience': 'Années d\'Expérience',
    'about.stats.trained': 'Professionnels Formés',
    'about.stats.partners': 'Entreprises Partenaires',
    'about.stats.trainings': 'Formations Disponibles',
    'about.mission.title': 'Notre Mission',
    'about.mission.description': 'Fournir des services d\'expertise technique et de formation de classe mondiale, en accompagnant nos clients dans leur développement professionnel et industriel. Nous nous engageons à délivrer des solutions innovantes et adaptées aux défis technologiques contemporains.',
    'about.vision.title': 'Notre Vision',
    'about.vision.description': 'Devenir le leader régional de l\'expertise technique et de la formation professionnelle, reconnu pour notre excellence, notre innovation et notre impact positif sur le développement des compétences industrielles en Afrique de l\'Ouest.',
    'about.values.title': 'Nos Valeurs',
    'about.values.subtitle': 'Les principes qui guident notre action quotidienne et définissent notre identité',
    'about.values.excellence': 'Excellence',
    'about.values.excellenceDesc': 'Nous visons l\'excellence dans chaque service que nous proposons, avec des standards de qualité élevés.',
    'about.values.innovation': 'Innovation',
    'about.values.innovationDesc': 'Nous intégrons les dernières technologies et méthodes pour rester à la pointe de notre domaine.',
    'about.values.partnership': 'Partenariat',
    'about.values.partnershipDesc': 'Nous construisons des relations durables basées sur la confiance et la collaboration.',
    'about.values.commitment': 'Engagement',
    'about.values.commitmentDesc': 'Nous nous engageons pleinement dans la réussite de nos clients et partenaires.',
    'about.team.title': 'Notre Équipe',
    'about.team.subtitle': 'Une équipe d\'experts passionnés et expérimentés, dédiée à votre succès',
    'about.team.role1': 'Directeur Général',
    'about.team.role2': 'Responsable Laboratoire',
    'about.team.role3': 'Chef de Formation',
    'about.team.multidisciplinary': 'Équipe Multidisciplinaire',
    'about.team.description': 'Notre équipe réunit des ingénieurs, des formateurs certifiés, des techniciens spécialisés et des consultants expérimentés. Chaque membre apporte son expertise unique pour vous offrir des services de la plus haute qualité.',
    'about.cta.title': 'Travaillons Ensemble',
    'about.cta.subtitle': 'Découvrez comment EXFORM peut vous accompagner dans vos projets',
    'about.cta.button': 'Contactez-nous',

    // Services
    'services.hero.badge': 'Services Techniques Avancés',
    'services.hero.title': 'Découvrez nos services de pointe',
    'services.hero.subtitle': 'Des solutions techniques innovantes et des formations de qualité pour accompagner votre développement',
    'services.laboratory.title': 'Laboratoire d\'analyse physico-chimique',
    'services.laboratory.description': 'Analyses physico-chimiques complètes selon les normes ISO et HACCP. Notre laboratoire moderne offre des services de contrôle qualité et de certification pour tous secteurs d\'activité.',
    'services.laboratory.feature1': 'Analyses conformes ISO 9001',
    'services.laboratory.feature2': 'Certifications HACCP',
    'services.laboratory.feature3': 'Contrôle qualité alimentaire',
    'services.laboratory.feature4': 'Analyses environnementales',
    'services.construction.title': 'BTP et équipements industriels',
    'services.construction.description': 'Solutions complètes pour vos projets BTP et équipements industriels. De la conception à la réalisation, nous vous accompagnons avec expertise et professionnalisme.',
    'services.construction.feature1': 'Études et conception',
    'services.construction.feature2': 'Réalisation de projets BTP',
    'services.construction.feature3': 'Installation d\'équipements',
    'services.construction.feature4': 'Maintenance industrielle',
    'services.training.title': 'Formation continue qualifiante',
    'services.training.description': 'Formations continues qualifiantes adaptées aux besoins du marché. Développez les compétences de vos équipes avec nos programmes certifiés et personnalisés.',
    'services.training.feature1': 'Formations certifiantes',
    'services.training.feature2': 'Programmes sur mesure',
    'services.training.feature3': 'Formateurs experts',
    'services.training.feature4': 'Suivi post-formation',
    'services.maintenance.title': 'Pluri-mécanique et maintenance industrielle',
    'services.maintenance.description': 'Services de maintenance préventive et corrective pour vos équipements industriels. Optimisez la performance et la durée de vie de vos installations.',
    'services.maintenance.feature1': 'Maintenance préventive',
    'services.maintenance.feature2': 'Dépannage d\'urgence',
    'services.maintenance.feature3': 'Optimisation performance',
    'services.maintenance.feature4': 'Contrats de maintenance',
    'services.burner.title': 'Maintenance des Brûleurs Industriels',
    'services.burner.description': 'Installation, contrôle annuel, maintenance des brûleurs gaz ou fuel des marques WEISHAUPT et SAAKE installés sur des chaudières ou des torréfacteurs',
    'services.burner.image1': 'Installation et maintenance de brûleurs WEISHAUPT',
    'services.burner.image2': 'Contrôle annuel des brûleurs SAAKE',
    'services.burner.image3': 'Maintenance des brûleurs industriels',
    'services.burner.installation': 'Installation',
    'services.burner.installationDesc': 'Installation professionnelle de brûleurs industriels',
    'services.burner.control': 'Contrôle Annuel',
    'services.burner.controlDesc': 'Contrôles périodiques et certifications',
    'services.burner.maintenanceTitle': 'Maintenance',
    'services.burner.maintenanceDesc': 'Maintenance préventive et corrective',
    'services.additional.title': 'Services Complémentaires',
    'services.additional.subtitle': 'Une gamme étendue de services pour répondre à tous vos besoins techniques et industriels',
    'services.additional.studies': 'Études et projets industriels (PGE-A et EIES)',
    'services.additional.consulting': 'Conseil en organisation industrielle',
    'services.additional.audit': 'Audit technique et énergétique',
    'services.additional.certification': 'Accompagnement certification qualité',
    'services.additional.safety': 'Formation en sécurité industrielle',
    'services.additional.support': 'Support technique spécialisé',
    'services.process.title': 'Notre Processus',
    'services.process.subtitle': 'Une approche structurée pour garantir la qualité et la satisfaction de nos clients',
    'services.process.step1': 'Analyse des Besoins',
    'services.process.step1Desc': 'Évaluation complète de vos besoins et objectifs',
    'services.process.step2': 'Proposition Solution',
    'services.process.step2Desc': 'Développement d\'une solution personnalisée',
    'services.process.step3': 'Mise en Œuvre',
    'services.process.step3Desc': 'Réalisation avec suivi qualité rigoureux',
    'services.process.step4': 'Suivi & Support',
    'services.process.step4Desc': 'Accompagnement continu et support technique',
    'services.cta.title': 'Prêt à Commencer Votre Projet ?',
    'services.cta.subtitle': 'Contactez nos experts pour une consultation personnalisée et un devis gratuit',

    // Training
    'training.title': 'Nos Formations',
    'training.subtitle': 'Développez vos compétences techniques avec nos formations certifiantes dispensées par des experts',
    'training.badge': 'Formation Continue',
    'training.register': 'Je m\'inscris',
    'training.vibration': 'Analyse vibratoire',
    'training.vibrationDesc': 'Formation complète sur l\'analyse vibratoire pour le diagnostic et la maintenance prédictive des équipements industriels.',
    'training.vibrationFeature1': 'Théorie des vibrations',
    'training.vibrationFeature2': 'Techniques de mesure',
    'training.vibrationFeature3': 'Analyse spectrale',
    'training.vibrationFeature4': 'Diagnostic des défauts',
    'training.hydraulics': 'Hydraulique',
    'training.hydraulicsDesc': 'Maîtrisez les systèmes hydrauliques industriels, de la conception à la maintenance en passant par la réparation.',
    'training.hydraulicsFeature1': 'Principes hydrauliques',
    'training.hydraulicsFeature2': 'Composants et circuits',
    'training.hydraulicsFeature3': 'Maintenance préventive',
    'training.hydraulicsFeature4': 'Dépannage pratique',
    'training.ammonia': 'Ammoniac',
    'training.ammoniaDesc': 'Formation spécialisée sur les risques liés à l\'ammoniac et les mesures de sécurité dans l\'industrie frigorifique.',
    'training.ammoniaFeature1': 'Propriétés de l\'ammoniac',
    'training.ammoniaFeature2': 'Procédures de sécurité',
    'training.ammoniaFeature3': 'Équipements de protection',
    'training.ammoniaFeature4': 'Gestion des urgences',
    'training.filtration': 'Filtration air',
    'training.filtrationDesc': 'Apprenez les techniques de filtration d\'air pour l\'industrie et les environnements contrôlés.',
    'training.filtrationFeature1': 'Types de filtres',
    'training.filtrationFeature2': 'Dimensionnement',
    'training.filtrationFeature3': 'Installation et maintenance',
    'training.filtrationFeature4': 'Contrôle qualité air',
    'training.pressure': 'Pression/Autoclave',
    'training.pressureDesc': 'Formation sur les équipements sous pression et autoclaves, réglementation et sécurité.',
    'training.pressureFeature1': 'Réglementation ESP',
    'training.pressureFeature2': 'Contrôles périodiques',
    'training.pressureFeature3': 'Maintenance sécurisée',
    'training.pressureFeature4': 'Certifications requises',
    'training.management': 'Management',
    'training.managementDesc': 'Développez vos compétences managériales pour diriger efficacement vos équipes techniques.',
    'training.managementFeature1': 'Leadership technique',
    'training.managementFeature2': 'Gestion d\'équipe',
    'training.managementFeature3': 'Communication efficace',
    'training.managementFeature4': 'Résolution de conflits',
    'training.duration.2days': '2 jours',
    'training.duration.3days': '3 jours',
    'training.duration.4days': '4 jours',
    'training.duration.5days': '5 jours',
    'training.level.intermediate': 'Intermédiaire',
    'training.level.all': 'Tous niveaux',
    'training.level.specialized': 'Spécialisé',
    'training.level.technical': 'Technique',
    'training.level.advanced': 'Avancé',
    'training.level.management': 'Management',
    'training.overview.title': 'Formation Continue Qualifiante',
    'training.overview.paragraph1': 'EXFORM propose un catalogue complet de formations techniques adaptées aux besoins du marché industriel. Nos programmes sont conçus pour développer vos compétences et vous maintenir à la pointe des technologies.',
    'training.overview.paragraph2': 'Que vous soyez débutant ou expert, nos formations modulaires vous permettent d\'évoluer à votre rythme avec un accompagnement personnalisé de nos formateurs certifiés.',
    'training.overview.paragraph3': 'Chaque formation débouche sur une certification reconnue par l\'industrie, valorisant ainsi vos nouvelles compétences auprès de vos employeurs ou clients.',
    'training.programs.title': 'Nos Programmes de Formation',
    'training.programs.subtitle': 'Choisissez parmi notre catalogue de formations techniques spécialisées',
    'training.whyChoose.title': 'Pourquoi Choisir Nos Formations ?',
    'training.whyChoose.subtitle': 'Les avantages qui font la différence dans votre parcours de formation',
    'training.advantages.experts': 'Formateurs Experts',
    'training.advantages.expertsDesc': 'Nos formateurs sont des professionnels expérimentés avec une expertise terrain reconnue.',
    'training.advantages.certifications': 'Certifications Reconnues',
    'training.advantages.certificationsDesc': 'Obtenez des certifications reconnues par l\'industrie et valorisez vos compétences.',
    'training.advantages.flexibility': 'Flexibilité Horaire',
    'training.advantages.flexibilityDesc': 'Formations adaptées à votre planning avec des sessions en journée ou en soirée.',
    'training.advantages.followup': 'Suivi Personnalisé',
    'training.advantages.followupDesc': 'Un accompagnement individualisé pour garantir votre progression et réussite.',
    'training.process.title': 'Processus de Formation',
    'training.process.subtitle': 'Un parcours structuré pour maximiser votre apprentissage',
    'training.process.step1': 'Inscription',
    'training.process.step1Desc': 'Choisissez votre formation et inscrivez-vous en ligne',
    'training.process.step2': 'Évaluation',
    'training.process.step2Desc': 'Évaluation de votre niveau pour adapter le programme',
    'training.process.step3': 'Formation',
    'training.process.step3Desc': 'Sessions théoriques et pratiques avec nos experts',
    'training.process.step4': 'Certification',
    'training.process.step4Desc': 'Examen final et remise de votre certification',
    'training.cta.title': 'Investissez dans Votre Avenir',
    'training.cta.subtitle': 'Rejoignez les milliers de professionnels qui ont développé leurs compétences avec EXFORM',
    'training.cta.info': 'Demander des informations',
    'training.faq.title': 'Questions Fréquentes',
    'training.faq.subtitle': 'Retrouvez les réponses aux questions les plus posées sur nos formations',
    'training.faq.q1': 'Quels sont les prérequis pour suivre une formation ?',
    'training.faq.a1': "Les prérequis varient selon la formation choisie. Certaines formations sont ouvertes à tous niveaux, tandis que d'autres nécessitent une expérience préalable dans le domaine. Contactez-nous pour plus de détails sur la formation qui vous intéresse.",
    'training.faq.q2': 'Les formations sont-elles certifiantes ?',
    'training.faq.a2': 'Oui, toutes nos formations délivrent une certification reconnue attestant de vos compétences acquises. Cette certification est un atout majeur pour votre carrière professionnelle.',
    'training.faq.q3': 'Proposez-vous des formations en entreprise ?',
    'training.faq.a3': 'Absolument ! Nous proposons des formations intra-entreprise adaptées à vos besoins spécifiques. Nos formateurs peuvent se déplacer dans vos locaux pour former vos équipes.',
    'training.faq.q4': 'Quels sont les modes de paiement acceptés ?',
    'training.faq.a4': 'Nous acceptons les virements bancaires, les chèques et les paiements en espèces. Des facilités de paiement peuvent être accordées sur demande. Les entreprises peuvent également bénéficier de la prise en charge par leur OPCO.',
    'training.faq.q5': "Comment se déroule l'inscription ?",
    'training.faq.a5': "L'inscription se fait en ligne via notre formulaire ou par téléphone. Après validation de votre dossier, vous recevrez une confirmation avec tous les détails pratiques de la formation.",
    'training.calendar.badge': 'Calendrier',
    'training.calendar.title': 'Prochaines Sessions',
    'training.calendar.subtitle': 'Consultez les dates de nos prochaines formations et réservez votre place',
    'training.calendar.spots': 'places',
    'training.calendar.book': 'Réserver',

    // Laboratory
    'laboratory.title': 'Laboratoire d\'Analyse',
    'laboratory.subtitle': 'Expertise physico-chimique, ISO, HACCP, analyses complètes de haute précision',
    'laboratory.badge': 'Laboratoire Certifié',
    'laboratory.discoverAnalysis': 'Découvrir nos analyses',
    'laboratory.discoverServices': 'Découvrir nos services',
    'laboratory.isoCertification': 'Certification ISO',
    'laboratory.qualityGuaranteed': 'Qualité garantie',
    'laboratory.overview.badge': 'Laboratoire de Pointe',
    'laboratory.overview.excellence': 'Excellence',
    'laboratory.overview.innovation': 'Innovation',
    'laboratory.overview.paragraph1': 'Notre laboratoire d\'analyse physico-chimique est équipé des technologies les plus avancées pour répondre à tous vos besoins d\'analyse et de contrôle qualité.',
    'laboratory.overview.paragraph2': 'Avec une équipe de techniciens qualifiés et des équipements de dernière génération, nous garantissons des résultats précis, fiables et dans les délais convenus.',
    'laboratory.overview.paragraph3': 'Nos services s\'adressent aux industries agroalimentaires, pharmaceutiques, cosmétiques, environnementales et à tous les secteurs nécessitant des analyses de qualité.',
    'laboratory.services.physicochemical.title': 'Analyses Physico-Chimiques',
    'laboratory.services.physicochemical.description': 'Analyses complètes des propriétés physiques et chimiques selon les normes internationales',
    'laboratory.services.physicochemical.feature1': 'pH et acidité',
    'laboratory.services.physicochemical.feature2': 'Composition minérale',
    'laboratory.services.physicochemical.feature3': 'Métaux lourds',
    'laboratory.services.physicochemical.feature4': 'Contaminants organiques',
    'laboratory.services.haccp.title': 'Contrôle Qualité HACCP',
    'laboratory.services.haccp.description': 'Analyses de sécurité alimentaire et respect des normes HACCP pour l\'industrie agroalimentaire',
    'laboratory.services.haccp.feature1': 'Analyses microbiologiques',
    'laboratory.services.haccp.feature2': 'Contaminants alimentaires',
    'laboratory.services.haccp.feature3': 'Additifs et conservateurs',
    'laboratory.services.haccp.feature4': 'Traçabilité produits',
    'laboratory.services.iso.title': 'Certifications ISO',
    'laboratory.services.iso.description': 'Services de certification et accompagnement pour les normes ISO 9001, 14001 et 22000',
    'laboratory.services.iso.feature1': 'Audit de conformité',
    'laboratory.services.iso.feature2': 'Mise en conformité',
    'laboratory.services.iso.feature3': 'Formation équipes',
    'laboratory.services.iso.feature4': 'Suivi certification',
    'laboratory.services.environmental.title': 'Analyses Environnementales',
    'laboratory.services.environmental.description': 'Contrôle de la qualité de l\'eau, de l\'air et des sols pour la protection environnementale',
    'laboratory.services.environmental.feature1': 'Qualité de l\'eau',
    'laboratory.services.environmental.feature2': 'Pollution atmosphérique',
    'laboratory.services.environmental.feature3': 'Contamination des sols',
    'laboratory.services.environmental.feature4': 'Impact environnemental',
    'laboratory.analysisTitle': 'Nos Analyses',
    'laboratory.servicesExcellence': 'Services d\'',
    'laboratory.excellence': 'Excellence',
    'laboratory.servicesSubtitle': 'Une gamme complète d\'analyses pour garantir la qualité et la conformité de vos produits avec les standards les plus élevés',
    'laboratory.equipmentTitle': 'Équipements de Pointe',
    'laboratory.equipmentSubtitle': 'Notre laboratoire dispose d\'équipements modernes et calibrés pour des analyses précises',
    'laboratory.equipment.spectrophotometer': 'Spectrophotomètre UV-Visible',
    'laboratory.equipment.chromatograph': 'Chromatographe en phase gazeuse',
    'laboratory.equipment.phMeter': 'pH-mètre de précision',
    'laboratory.equipment.balance': 'Balance analytique',
    'laboratory.equipment.microscope': 'Microscope électronique',
    'laboratory.equipment.autoclave': 'Autoclave de stérilisation',
    'laboratory.certificationsTitle': 'Certifications & Accréditations',
    'laboratory.certificationsSubtitle': 'Notre laboratoire respecte les plus hautes normes de qualité et de sécurité',
    'laboratory.certifications.iso17025': 'Compétence des laboratoires d\'essais et d\'étalonnage',
    'laboratory.certifications.iso9001': 'Système de management de la qualité',
    'laboratory.certifications.haccp': 'Analyse des dangers et maîtrise des points critiques',
    'laboratory.certifications.glp': 'Bonnes pratiques de laboratoire',
    'laboratory.processTitle': 'Processus d\'Analyse',
    'laboratory.processSubtitle': 'Un processus rigoureux pour garantir la qualité de nos analyses',
    'laboratory.process.reception': 'Réception',
    'laboratory.process.receptionDesc': 'Réception et enregistrement de l\'échantillon',
    'laboratory.process.preparation': 'Préparation',
    'laboratory.process.preparationDesc': 'Préparation selon les protocoles standards',
    'laboratory.process.analysis': 'Analyse',
    'laboratory.process.analysisDesc': 'Analyse avec équipements calibrés',
    'laboratory.process.control': 'Contrôle',
    'laboratory.process.controlDesc': 'Contrôle qualité et validation',
    'laboratory.process.report': 'Rapport',
    'laboratory.process.reportDesc': 'Rapport détaillé et certifié',
    'laboratory.cta.title': 'Besoin d\'Analyses de Qualité ?',
    'laboratory.cta.subtitle': 'Contactez-nous pour discuter de vos besoins d\'analyse et obtenir un devis personnalisé adapté à vos exigences',
    'laboratory.cta.quote': 'Demander un devis',
    'laboratory.cta.allServices': 'Tous nos services',

    // Contact
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Nous sommes à votre écoute pour répondre à toutes vos questions et vous accompagner dans vos projets',
    'contact.address': 'Yopougon – en face du CHU',
    'contact.form.title': 'Envoyez-nous un Message',
    'contact.form.name': 'Nom complet',
    'contact.form.name.placeholder': 'Votre nom complet',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'votre.email@exemple.com',
    'contact.form.phone': 'Téléphone',
    'contact.form.phone.placeholder': 'Votre numéro de téléphone',
    'contact.form.subject': 'Sujet',
    'contact.form.subject.placeholder': 'Sujet de votre message',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Décrivez votre besoin ou votre question...',
    'contact.form.send': 'Envoyer le message',
    'contact.form.sending': 'Envoi en cours...',
    'contact.info.title': 'Nos Coordonnées',
    'contact.info.address': 'Adresse',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Téléphone',
    'contact.info.hours': 'Horaires',
    'contact.hours.weekday': 'Lundi - Vendredi: 8h - 18h',
    'contact.hours.saturday': 'Samedi: 8h - 13h',
    'contact.map.title': 'Notre Localisation',
    'contact.map.subtitle': 'Retrouvez-nous facilement à Yopougon, en face du CHU',
    'contact.map.placeholder': 'Intégration Google Maps',
    'contact.map.coming': 'Carte interactive disponible prochainement',
    'contact.faq.title': 'Questions Fréquentes',
    'contact.faq.q1': 'Quels sont vos délais de réponse ?',
    'contact.faq.a1': 'Nous nous engageons à répondre à toute demande dans les 24h ouvrées.',
    'contact.faq.q2': 'Proposez-vous des formations sur site ?',
    'contact.faq.a2': 'Oui, nous pouvons organiser des formations directement dans vos locaux selon vos besoins.',
    'contact.faq.q3': 'Comment obtenir un devis pour une analyse ?',
    'contact.faq.a3': 'Contactez-nous avec les détails de votre besoin, nous vous fournirons un devis gratuit sous 48h.',
    'contact.quick.training': 'S\'inscrire à une formation',
    'contact.quick.analysis': 'Demander une analyse',
    'contact.toast.success': 'Message envoyé !',
    'contact.toast.description': 'Nous vous contacterons très bientôt.',

    // Home
    'home.stats.clients': 'Clients Satisfaits',
    'home.stats.experience': 'Années d\'Expérience',
    'home.stats.formations': 'Formations Dispensées',
    'home.services.badge': 'Nos Services',
    'home.services.title': 'Découvrez nos services de pointe',
    'home.services.subtitle': 'Découvrez notre gamme complète de services techniques et de formations professionnelles',
    'home.why.title': 'Pourquoi Choisir EXFORM ?',
    'home.why.subtitle': 'Avec plus de 15 ans d\'expérience, EXFORM s\'impose comme le partenaire de référence pour vos besoins en expertise technique et formation professionnelle.',
    'home.why.point1': 'Expertise technique certifiée et reconnue',
    'home.why.point2': 'Formations adaptées aux besoins du marché',
    'home.why.point3': 'Laboratoire équipé aux normes internationales',
    'home.why.point4': 'Accompagnement personnalisé de vos projets',
    'home.partners.title': 'Nos Partenaires de Confiance',
    'home.partners.subtitle': 'Nous collaborons avec les leaders de l\'industrie pour vous offrir les meilleures solutions',
    'home.faq.title': 'Questions Fréquemment Posées',
    'home.faq.subtitle': 'Trouvez rapidement des réponses à vos questions',
    'home.faq.more': 'Vous avez d\'autres questions ?',
    'home.faq.q1': 'Quelles sont vos accréditations et certifications ?',
    'home.faq.a1': 'EXFORM dispose des certifications ISO 9001 et ISO 17025 pour nos laboratoires. Nous sommes également accrédités COFRAC et reconnus par les organismes internationaux de normalisation.',
    'home.faq.q2': 'Combien de temps durent vos formations ?',
    'home.faq.a2': 'Nos formations varient de 2 jours à plusieurs semaines selon le programme. Nous proposons également des formations sur mesure adaptées à vos besoins spécifiques.',
    'home.faq.q3': 'Proposez-vous un accompagnement post-formation ?',
    'home.faq.a3': 'Oui, nous offrons un suivi personnalisé après chaque formation incluant un accès à nos ressources en ligne et un support technique pendant 3 mois.',
    'home.faq.q4': 'Quels types d\'analyses effectuez-vous dans votre laboratoire ?',
    'home.faq.a4': 'Notre laboratoire réalise des analyses physico-chimiques, microbiologiques, environnementales et des matériaux de construction selon les normes internationales.',
    'home.faq.q5': 'Comment obtenir un devis pour vos services ?',
    'home.faq.a5': 'Vous pouvez demander un devis gratuit via notre formulaire de contact ou en nous appelant directement. Nous vous répondons sous 24h.',
    'home.cta.title': 'Prêt à Développer Vos Compétences ?',
    'home.cta.subtitle': 'Contactez-nous dès aujourd\'hui pour discuter de vos besoins en formation et expertise technique',
    'home.cta.contact': 'Nous contacter',
    'home.cta.trainings': 'Voir nos formations',

    // Registration
    'register.title': 'Inscription à une formation',
    'register.subtitle': 'Bonjour, veuillez remplir le formulaire pour vous inscrire à une formation',
    'register.submit': 'S\'inscrire',
    'register.step1.title': 'Informations Personnelles',
    'register.step1.label': 'Informations personnelles',
    'register.step2.title': 'Informations Professionnelles',
    'register.step2.label': 'Informations professionnelles',
    'register.step3.title': 'Choix de Formation',
    'register.step3.label': 'Choix de formation',
    'register.firstName': 'Prénom',
    'register.firstName.placeholder': 'Votre prénom',
    'register.lastName': 'Nom',
    'register.lastName.placeholder': 'Votre nom',
    'register.email': 'Email',
    'register.email.placeholder': 'votre.email@exemple.com',
    'register.phone': 'Téléphone',
    'register.phone.placeholder': '+225 07 00 00 00 00',
    'register.company': 'Entreprise',
    'register.company.placeholder': 'Nom de votre entreprise',
    'register.position': 'Poste occupé',
    'register.position.placeholder': 'Votre poste actuel',
    'register.experience': 'Années d\'expérience',
    'register.experience.placeholder': 'Sélectionnez votre niveau d\'expérience',
    'register.experience.0-2': '0-2 ans',
    'register.experience.3-5': '3-5 ans',
    'register.experience.6-10': '6-10 ans',
    'register.experience.10+': 'Plus de 10 ans',
    'register.training': 'Formation souhaitée',
    'register.training.placeholder': 'Choisissez votre formation',
    'register.startDate': 'Date de début souhaitée',
    'register.motivation': 'Motivation / Objectifs',
    'register.motivation.placeholder': 'Décrivez vos objectifs et motivations pour cette formation...',
    'register.characters': 'caractères',
    'register.summary': 'Récapitulatif',
    'register.fullName': 'Nom complet',
    'register.previous': 'Précédent',
    'register.next': 'Suivant',
    'register.backToTraining': 'Retour aux formations',
    'register.submitting': 'Inscription en cours...',
    'register.toast.success': 'Inscription réussie !',
    'register.toast.description': 'Nous vous contacterons sous 48h pour confirmer votre inscription.',

    // Thanks
    'thanks.title': 'Merci !',
    'thanks.message': 'Nous vous contacterons très bientôt',
    'thanks.nextSteps': 'Prochaines Étapes',
    'thanks.step1.title': 'Confirmation sous 48h',
    'thanks.step1.desc': 'Notre équipe vous contactera pour confirmer votre inscription et les modalités pratiques.',
    'thanks.step2.title': 'Préparation de la formation',
    'thanks.step2.desc': 'Réception des documents et du matériel pédagogique avant le début de la formation.',
    'thanks.step3.title': 'Début de votre formation',
    'thanks.step3.desc': 'Accompagnement personnalisé tout au long de votre parcours d\'apprentissage.',
    'thanks.contactQuestion': 'Une question ? Contactez-nous',
    'thanks.otherTrainings': 'Voir d\'autres formations',
    'thanks.aboutExform': 'À propos d\'EXFORM',
    'thanks.aboutExformDesc': 'Découvrez notre histoire et nos valeurs',
    'thanks.ourServices': 'Nos Services',
    'thanks.ourServicesDesc': 'Explorez toute notre gamme de services',
    'thanks.contactUs': 'Nous Contacter',
    'thanks.contactUsDesc': 'Toutes nos coordonnées et localisation',

    // Footer
    'footer.navigation': 'Navigation',
    'footer.copyright': 'Tous droits réservés.',
    'footer.legal': 'Mentions légales',
    'footer.privacy': 'Politique de confidentialité',

    // Chatbot
    'chatbot.greeting': 'Bonjour! Je suis l\'assistant virtuel d\'EXFORM. Comment puis-je vous aider aujourd\'hui?',
    'chatbot.online': 'En ligne',
    'chatbot.placeholder': 'Tapez votre message...',
    'chatbot.services': 'EXFORM offre trois services principaux : Laboratoire d\'analyse physico-chimique, Formation continue qualifiante, et BTP & équipements industriels. Voulez-vous en savoir plus sur l\'un de ces services ?',
    'chatbot.laboratory': 'Notre laboratoire propose des analyses complètes selon les normes ISO et HACCP. Nous couvrons les analyses d\'eau, air, poussière, son et environnement.',
    'chatbot.training': 'Nos formations incluent l\'analyse vibratoire, hydraulique, systèmes d\'étanchéité, risques liés à l\'ammoniac, et bien plus. Souhaitez-vous vous inscrire ?',
    'chatbot.contact': 'Vous pouvez nous contacter à Yopougon en face du CHU, ou utiliser notre formulaire de contact en ligne. Notre équipe vous répondra rapidement.',
    'chatbot.default': 'Je vous remercie pour votre question. Pour des informations détaillées, je vous invite à nous contacter directement ou à consulter nos pages de services.',

    // WhatsApp
    'whatsapp.title': 'Contactez-nous sur WhatsApp',
    'whatsapp.message': 'Bonjour, je vous contacte depuis votre site web EXFORM. J\'aimerais avoir des informations sur vos services.',

    // Common
    'common.learnMore': 'En savoir plus',
    'common.backHome': 'Retour à l\'accueil',
    'common.servicesBadge': 'Nos Services',
    'common.contact': 'Contact',
    'common.contactUs': 'Contactez-nous',

    // SEO
    'seo.home.title': 'EXFORM - Expertise Technique & Formation aux Métiers | Côte d\'Ivoire',
    'seo.home.description': 'EXFORM, leader en expertise technique et formation professionnelle en Côte d\'Ivoire. Laboratoire d\'analyse physico-chimique certifié ISO, formations continues qualifiantes.',
    'seo.about.title': 'À Propos d\'EXFORM | Notre Histoire et Nos Valeurs',
    'seo.about.description': 'Découvrez l\'histoire d\'EXFORM, notre mission, notre vision et nos valeurs. Plus de 15 ans d\'expérience en expertise technique et formation en Côte d\'Ivoire.',
    'seo.services.title': 'Nos Services | Laboratoire, BTP, Maintenance Industrielle - EXFORM',
    'seo.services.description': 'Découvrez nos services : laboratoire d\'analyse physico-chimique, BTP et équipements industriels, maintenance des brûleurs. Solutions techniques complètes.',
    'seo.laboratory.title': 'Laboratoire d\'Analyse Physico-Chimique | EXFORM Côte d\'Ivoire',
    'seo.laboratory.description': 'Laboratoire certifié ISO et HACCP. Analyses physico-chimiques, contrôle qualité alimentaire, analyses environnementales de haute précision.',
    'seo.training.title': 'Formations Professionnelles Certifiantes | EXFORM',
    'seo.training.description': 'Formations continues qualifiantes : analyse vibratoire, hydraulique, ammoniac, management. Formateurs experts et certifications reconnues.',
    'seo.contact.title': 'Contactez EXFORM | Devis Gratuit et Informations',
    'seo.contact.description': 'Contactez EXFORM à Abidjan, Yopougon. Demandez un devis gratuit pour nos services de laboratoire, formation et maintenance industrielle.',
    'seo.register.title': 'Inscription Formation | EXFORM',
    'seo.register.description': 'Inscrivez-vous à nos formations professionnelles certifiantes. Développez vos compétences avec les experts d\'EXFORM.',
    'seo.thanks.title': 'Merci pour votre inscription | EXFORM',
    'seo.thanks.description': 'Votre inscription a été enregistrée. Notre équipe vous contactera sous 48h pour confirmer les détails.',
    'seo.notfound.title': 'Page Non Trouvée | EXFORM',
    'seo.notfound.description': 'La page que vous recherchez n\'existe pas. Retournez à l\'accueil pour explorer nos services.',

    // 404 Page
    'notfound.title': 'Page non trouvée',
    'notfound.description': 'Désolé, la page que vous recherchez n\'existe pas ou a été déplacée. Vérifiez l\'URL ou retournez à l\'accueil.',
    'notfound.home': 'Retour à l\'accueil',
    'notfound.contact': 'Nous contacter',
    'notfound.suggestions': 'Pages qui pourraient vous intéresser :',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.laboratory': 'Laboratory',
    'nav.training': 'Training',
    'nav.contact': 'Contact',

    // Hero Section
    'hero.title': 'Technical Expertise & Professional Training',
    'hero.subtitle': 'Excellence, Innovation and Professionalism serving your development',
    'hero.cta': 'Explore our Services',

    // About
    'about.title': 'About EXFORM',
    'about.subtitle': 'Our mission, our values, our vision',
    'about.badge': 'About EXFORM',
    'about.story.badge': 'Our Journey',
    'about.story.title': 'Our Story',
    'about.story.paragraph1': 'Founded with the vision of transforming the technical training and industrial expertise landscape in Ivory Coast, EXFORM has quickly established itself as a key player in the sector.',
    'about.story.paragraph2': 'Since our beginnings, we have trained over 500 professionals and supported hundreds of companies in their development. Our physico-chemical analysis laboratory is recognized for its precision and compliance with international standards.',
    'about.story.paragraph3': 'Today, EXFORM continues to evolve to meet the technological and industrial challenges of tomorrow, while maintaining our commitment to excellence and innovation.',
    'about.stats.experience': 'Years of Experience',
    'about.stats.trained': 'Professionals Trained',
    'about.stats.partners': 'Partner Companies',
    'about.stats.trainings': 'Available Training Programs',
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'Provide world-class technical expertise and training services, supporting our clients in their professional and industrial development. We are committed to delivering innovative solutions adapted to contemporary technological challenges.',
    'about.vision.title': 'Our Vision',
    'about.vision.description': 'Become the regional leader in technical expertise and professional training, recognized for our excellence, innovation and positive impact on industrial skills development in West Africa.',
    'about.values.title': 'Our Values',
    'about.values.subtitle': 'The principles that guide our daily action and define our identity',
    'about.values.excellence': 'Excellence',
    'about.values.excellenceDesc': 'We strive for excellence in every service we offer, with high quality standards.',
    'about.values.innovation': 'Innovation',
    'about.values.innovationDesc': 'We integrate the latest technologies and methods to stay at the forefront of our field.',
    'about.values.partnership': 'Partnership',
    'about.values.partnershipDesc': 'We build lasting relationships based on trust and collaboration.',
    'about.values.commitment': 'Commitment',
    'about.values.commitmentDesc': 'We are fully committed to the success of our clients and partners.',
    'about.team.title': 'Our Team',
    'about.team.subtitle': 'A team of passionate and experienced experts, dedicated to your success',
    'about.team.role1': 'General Manager',
    'about.team.role2': 'Laboratory Manager',
    'about.team.role3': 'Training Manager',
    'about.team.multidisciplinary': 'Multidisciplinary Team',
    'about.team.description': 'Our team brings together engineers, certified trainers, specialized technicians and experienced consultants. Each member brings their unique expertise to offer you the highest quality services.',
    'about.cta.title': "Let's Work Together",
    'about.cta.subtitle': 'Discover how EXFORM can support you in your projects',
    'about.cta.button': 'Contact us',

    // Services
    'services.hero.badge': 'Advanced Technical Services',
    'services.hero.title': 'Discover our cutting-edge services',
    'services.hero.subtitle': 'Innovative technical solutions and quality training to support your development',
    'services.laboratory.title': 'Physico-chemical Analysis Laboratory',
    'services.laboratory.description': 'Complete physico-chemical analyses according to ISO and HACCP standards. Our modern laboratory offers quality control and certification services for all business sectors.',
    'services.laboratory.feature1': 'ISO 9001 compliant analyses',
    'services.laboratory.feature2': 'HACCP certifications',
    'services.laboratory.feature3': 'Food quality control',
    'services.laboratory.feature4': 'Environmental analyses',
    'services.construction.title': 'Construction & Industrial Equipment',
    'services.construction.description': 'Complete solutions for your construction and industrial equipment projects. From design to implementation, we support you with expertise and professionalism.',
    'services.construction.feature1': 'Studies and design',
    'services.construction.feature2': 'Construction project execution',
    'services.construction.feature3': 'Equipment installation',
    'services.construction.feature4': 'Industrial maintenance',
    'services.training.title': 'Continuous Professional Training',
    'services.training.description': 'Continuous professional training adapted to market needs. Develop your teams\' skills with our certified and personalized programs.',
    'services.training.feature1': 'Certified training',
    'services.training.feature2': 'Custom programs',
    'services.training.feature3': 'Expert trainers',
    'services.training.feature4': 'Post-training follow-up',
    'services.maintenance.title': 'Multi-mechanics & Industrial Maintenance',
    'services.maintenance.description': 'Preventive and corrective maintenance services for your industrial equipment. Optimize the performance and lifespan of your installations.',
    'services.maintenance.feature1': 'Preventive maintenance',
    'services.maintenance.feature2': 'Emergency repair',
    'services.maintenance.feature3': 'Performance optimization',
    'services.maintenance.feature4': 'Maintenance contracts',
    'services.burner.title': 'Industrial Burner Maintenance',
    'services.burner.description': 'Installation, annual inspection, maintenance of gas or fuel burners from WEISHAUPT and SAAKE brands installed on boilers or roasters',
    'services.burner.image1': 'WEISHAUPT burner installation and maintenance',
    'services.burner.image2': 'SAAKE burner annual inspection',
    'services.burner.image3': 'Industrial burner maintenance',
    'services.burner.installation': 'Installation',
    'services.burner.installationDesc': 'Professional installation of industrial burners',
    'services.burner.control': 'Annual Inspection',
    'services.burner.controlDesc': 'Periodic inspections and certifications',
    'services.burner.maintenanceTitle': 'Maintenance',
    'services.burner.maintenanceDesc': 'Preventive and corrective maintenance',
    'services.additional.title': 'Additional Services',
    'services.additional.subtitle': 'An extended range of services to meet all your technical and industrial needs',
    'services.additional.studies': 'Industrial studies and projects (PGE-A and EIES)',
    'services.additional.consulting': 'Industrial organization consulting',
    'services.additional.audit': 'Technical and energy audit',
    'services.additional.certification': 'Quality certification support',
    'services.additional.safety': 'Industrial safety training',
    'services.additional.support': 'Specialized technical support',
    'services.process.title': 'Our Process',
    'services.process.subtitle': 'A structured approach to ensure quality and customer satisfaction',
    'services.process.step1': 'Needs Analysis',
    'services.process.step1Desc': 'Complete assessment of your needs and objectives',
    'services.process.step2': 'Solution Proposal',
    'services.process.step2Desc': 'Development of a customized solution',
    'services.process.step3': 'Implementation',
    'services.process.step3Desc': 'Execution with rigorous quality monitoring',
    'services.process.step4': 'Follow-up & Support',
    'services.process.step4Desc': 'Ongoing support and technical assistance',
    'services.cta.title': 'Ready to Start Your Project?',
    'services.cta.subtitle': 'Contact our experts for a personalized consultation and free quote',

    // Training
    'training.title': 'Our Training Programs',
    'training.subtitle': 'Develop your technical skills with our certified training delivered by experts',
    'training.badge': 'Continuous Training',
    'training.register': 'Register now',
    'training.vibration': 'Vibration Analysis',
    'training.vibrationDesc': 'Complete training on vibration analysis for diagnosis and predictive maintenance of industrial equipment.',
    'training.vibrationFeature1': 'Vibration theory',
    'training.vibrationFeature2': 'Measurement techniques',
    'training.vibrationFeature3': 'Spectral analysis',
    'training.vibrationFeature4': 'Fault diagnosis',
    'training.hydraulics': 'Hydraulics',
    'training.hydraulicsDesc': 'Master industrial hydraulic systems, from design to maintenance and repair.',
    'training.hydraulicsFeature1': 'Hydraulic principles',
    'training.hydraulicsFeature2': 'Components and circuits',
    'training.hydraulicsFeature3': 'Preventive maintenance',
    'training.hydraulicsFeature4': 'Practical troubleshooting',
    'training.ammonia': 'Ammonia Safety',
    'training.ammoniaDesc': 'Specialized training on ammonia-related risks and safety measures in the refrigeration industry.',
    'training.ammoniaFeature1': 'Ammonia properties',
    'training.ammoniaFeature2': 'Safety procedures',
    'training.ammoniaFeature3': 'Protective equipment',
    'training.ammoniaFeature4': 'Emergency management',
    'training.filtration': 'Air Filtration',
    'training.filtrationDesc': 'Learn air filtration techniques for industry and controlled environments.',
    'training.filtrationFeature1': 'Filter types',
    'training.filtrationFeature2': 'Sizing',
    'training.filtrationFeature3': 'Installation and maintenance',
    'training.filtrationFeature4': 'Air quality control',
    'training.pressure': 'Pressure/Autoclave',
    'training.pressureDesc': 'Training on pressure equipment and autoclaves, regulations and safety.',
    'training.pressureFeature1': 'PED regulations',
    'training.pressureFeature2': 'Periodic inspections',
    'training.pressureFeature3': 'Safe maintenance',
    'training.pressureFeature4': 'Required certifications',
    'training.management': 'Management',
    'training.managementDesc': 'Develop your management skills to effectively lead your technical teams.',
    'training.managementFeature1': 'Technical leadership',
    'training.managementFeature2': 'Team management',
    'training.managementFeature3': 'Effective communication',
    'training.managementFeature4': 'Conflict resolution',
    'training.duration.2days': '2 days',
    'training.duration.3days': '3 days',
    'training.duration.4days': '4 days',
    'training.duration.5days': '5 days',
    'training.level.intermediate': 'Intermediate',
    'training.level.all': 'All levels',
    'training.level.specialized': 'Specialized',
    'training.level.technical': 'Technical',
    'training.level.advanced': 'Advanced',
    'training.level.management': 'Management',
    'training.overview.title': 'Continuous Professional Training',
    'training.overview.paragraph1': 'EXFORM offers a complete catalog of technical training adapted to industrial market needs. Our programs are designed to develop your skills and keep you at the cutting edge of technology.',
    'training.overview.paragraph2': 'Whether you are a beginner or an expert, our modular training programs allow you to progress at your own pace with personalized support from our certified trainers.',
    'training.overview.paragraph3': 'Each training leads to an industry-recognized certification, thus enhancing your new skills with your employers or clients.',
    'training.programs.title': 'Our Training Programs',
    'training.programs.subtitle': 'Choose from our catalog of specialized technical training',
    'training.whyChoose.title': 'Why Choose Our Training?',
    'training.whyChoose.subtitle': 'The advantages that make a difference in your training journey',
    'training.advantages.experts': 'Expert Trainers',
    'training.advantages.expertsDesc': 'Our trainers are experienced professionals with recognized field expertise.',
    'training.advantages.certifications': 'Recognized Certifications',
    'training.advantages.certificationsDesc': 'Obtain industry-recognized certifications and enhance your skills.',
    'training.advantages.flexibility': 'Schedule Flexibility',
    'training.advantages.flexibilityDesc': 'Training adapted to your schedule with day or evening sessions.',
    'training.advantages.followup': 'Personalized Follow-up',
    'training.advantages.followupDesc': 'Individual support to ensure your progress and success.',
    'training.process.title': 'Training Process',
    'training.process.subtitle': 'A structured path to maximize your learning',
    'training.process.step1': 'Registration',
    'training.process.step1Desc': 'Choose your training and register online',
    'training.process.step2': 'Assessment',
    'training.process.step2Desc': 'Assessment of your level to adapt the program',
    'training.process.step3': 'Training',
    'training.process.step3Desc': 'Theoretical and practical sessions with our experts',
    'training.process.step4': 'Certification',
    'training.process.step4Desc': 'Final exam and delivery of your certification',
    'training.cta.title': 'Invest in Your Future',
    'training.cta.subtitle': 'Join the thousands of professionals who have developed their skills with EXFORM',
    'training.cta.info': 'Request information',
    'training.faq.title': 'Frequently Asked Questions',
    'training.faq.subtitle': 'Find answers to the most common questions about our training programs',
    'training.faq.q1': 'What are the prerequisites for attending a training?',
    'training.faq.a1': 'Prerequisites vary depending on the chosen training. Some training programs are open to all levels, while others require prior experience in the field. Contact us for more details about the training you are interested in.',
    'training.faq.q2': 'Are the trainings certified?',
    'training.faq.a2': 'Yes, all our training programs deliver a recognized certification attesting to your acquired skills. This certification is a major asset for your professional career.',
    'training.faq.q3': 'Do you offer in-company training?',
    'training.faq.a3': 'Absolutely! We offer in-company training adapted to your specific needs. Our trainers can come to your premises to train your teams.',
    'training.faq.q4': 'What payment methods are accepted?',
    'training.faq.a4': 'We accept bank transfers, checks and cash payments. Payment facilities can be granted upon request. Companies can also benefit from coverage by their training fund.',
    'training.faq.q5': 'How does registration work?',
    'training.faq.a5': 'Registration is done online via our form or by phone. After validation of your file, you will receive a confirmation with all the practical details of the training.',
    'training.calendar.badge': 'Calendar',
    'training.calendar.title': 'Upcoming Sessions',
    'training.calendar.subtitle': 'Check the dates of our upcoming training sessions and book your spot',
    'training.calendar.spots': 'spots',
    'training.calendar.book': 'Book Now',

    // Laboratory
    'laboratory.title': 'Analysis Laboratory',
    'laboratory.subtitle': 'Physico-chemical expertise, ISO, HACCP, high-precision comprehensive analyses',
    'laboratory.badge': 'Certified Laboratory',
    'laboratory.discoverAnalysis': 'Discover our analyses',
    'laboratory.discoverServices': 'Discover our services',
    'laboratory.isoCertification': 'ISO Certification',
    'laboratory.qualityGuaranteed': 'Quality guaranteed',
    'laboratory.overview.badge': 'State-of-the-Art Laboratory',
    'laboratory.overview.excellence': 'Excellence',
    'laboratory.overview.innovation': 'Innovation',
    'laboratory.overview.paragraph1': 'Our physico-chemical analysis laboratory is equipped with the most advanced technologies to meet all your analysis and quality control needs.',
    'laboratory.overview.paragraph2': 'With a team of qualified technicians and state-of-the-art equipment, we guarantee precise, reliable results within agreed timeframes.',
    'laboratory.overview.paragraph3': 'Our services cater to food, pharmaceutical, cosmetic, environmental industries and all sectors requiring quality analyses.',
    'laboratory.services.physicochemical.title': 'Physico-Chemical Analyses',
    'laboratory.services.physicochemical.description': 'Complete analyses of physical and chemical properties according to international standards',
    'laboratory.services.physicochemical.feature1': 'pH and acidity',
    'laboratory.services.physicochemical.feature2': 'Mineral composition',
    'laboratory.services.physicochemical.feature3': 'Heavy metals',
    'laboratory.services.physicochemical.feature4': 'Organic contaminants',
    'laboratory.services.haccp.title': 'HACCP Quality Control',
    'laboratory.services.haccp.description': 'Food safety analyses and HACCP compliance for the food industry',
    'laboratory.services.haccp.feature1': 'Microbiological analyses',
    'laboratory.services.haccp.feature2': 'Food contaminants',
    'laboratory.services.haccp.feature3': 'Additives and preservatives',
    'laboratory.services.haccp.feature4': 'Product traceability',
    'laboratory.services.iso.title': 'ISO Certifications',
    'laboratory.services.iso.description': 'Certification services and support for ISO 9001, 14001 and 22000 standards',
    'laboratory.services.iso.feature1': 'Compliance audit',
    'laboratory.services.iso.feature2': 'Compliance implementation',
    'laboratory.services.iso.feature3': 'Team training',
    'laboratory.services.iso.feature4': 'Certification follow-up',
    'laboratory.services.environmental.title': 'Environmental Analyses',
    'laboratory.services.environmental.description': 'Water, air and soil quality control for environmental protection',
    'laboratory.services.environmental.feature1': 'Water quality',
    'laboratory.services.environmental.feature2': 'Air pollution',
    'laboratory.services.environmental.feature3': 'Soil contamination',
    'laboratory.services.environmental.feature4': 'Environmental impact',
    'laboratory.analysisTitle': 'Our Analyses',
    'laboratory.servicesExcellence': 'Services of ',
    'laboratory.excellence': 'Excellence',
    'laboratory.servicesSubtitle': 'A complete range of analyses to guarantee the quality and compliance of your products with the highest standards',
    'laboratory.equipmentTitle': 'State-of-the-Art Equipment',
    'laboratory.equipmentSubtitle': 'Our laboratory has modern, calibrated equipment for precise analyses',
    'laboratory.equipment.spectrophotometer': 'UV-Visible Spectrophotometer',
    'laboratory.equipment.chromatograph': 'Gas Chromatograph',
    'laboratory.equipment.phMeter': 'Precision pH Meter',
    'laboratory.equipment.balance': 'Analytical Balance',
    'laboratory.equipment.microscope': 'Electron Microscope',
    'laboratory.equipment.autoclave': 'Sterilization Autoclave',
    'laboratory.certificationsTitle': 'Certifications & Accreditations',
    'laboratory.certificationsSubtitle': 'Our laboratory meets the highest quality and safety standards',
    'laboratory.certifications.iso17025': 'Testing and calibration laboratory competence',
    'laboratory.certifications.iso9001': 'Quality management system',
    'laboratory.certifications.haccp': 'Hazard analysis and critical control points',
    'laboratory.certifications.glp': 'Good laboratory practice',
    'laboratory.processTitle': 'Analysis Process',
    'laboratory.processSubtitle': 'A rigorous process to guarantee the quality of our analyses',
    'laboratory.process.reception': 'Reception',
    'laboratory.process.receptionDesc': 'Sample reception and registration',
    'laboratory.process.preparation': 'Preparation',
    'laboratory.process.preparationDesc': 'Preparation according to standard protocols',
    'laboratory.process.analysis': 'Analysis',
    'laboratory.process.analysisDesc': 'Analysis with calibrated equipment',
    'laboratory.process.control': 'Control',
    'laboratory.process.controlDesc': 'Quality control and validation',
    'laboratory.process.report': 'Report',
    'laboratory.process.reportDesc': 'Detailed and certified report',
    'laboratory.cta.title': 'Need Quality Analyses?',
    'laboratory.cta.subtitle': 'Contact us to discuss your analysis needs and get a personalized quote tailored to your requirements',
    'laboratory.cta.quote': 'Request a quote',
    'laboratory.cta.allServices': 'All our services',

    // Contact
    'contact.title': 'Contact us',
    'contact.subtitle': 'We are here to listen and answer all your questions and support you in your projects',
    'contact.address': 'Yopougon – opposite CHU Hospital',
    'contact.form.title': 'Send us a Message',
    'contact.form.name': 'Full name',
    'contact.form.name.placeholder': 'Your full name',
    'contact.form.email': 'Email address',
    'contact.form.email.placeholder': 'your.email@example.com',
    'contact.form.phone': 'Phone number',
    'contact.form.phone.placeholder': 'Your phone number',
    'contact.form.subject': 'Subject',
    'contact.form.subject.placeholder': 'Subject of your message',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Describe your needs or ask your question...',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.info.title': 'Our Contact Information',
    'contact.info.address': 'Address',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.hours': 'Business Hours',
    'contact.hours.weekday': 'Monday - Friday: 8am - 6pm',
    'contact.hours.saturday': 'Saturday: 8am - 1pm',
    'contact.map.title': 'Our Location',
    'contact.map.subtitle': 'Find us easily in Yopougon, opposite CHU Hospital',
    'contact.map.placeholder': 'Google Maps Integration',
    'contact.map.coming': 'Interactive map coming soon',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.q1': 'What are your response times?',
    'contact.faq.a1': 'We are committed to responding to any request within 24 working hours.',
    'contact.faq.q2': 'Do you offer on-site training?',
    'contact.faq.a2': 'Yes, we can organize training directly at your premises according to your needs.',
    'contact.faq.q3': 'How to get a quote for analysis?',
    'contact.faq.a3': 'Contact us with the details of your needs, we will provide you with a free quote within 48 hours.',
    'contact.quick.training': 'Register for training',
    'contact.quick.analysis': 'Request analysis',
    'contact.toast.success': 'Message sent!',
    'contact.toast.description': 'We will contact you very soon.',

    // Home
    'home.stats.clients': 'Satisfied Clients',
    'home.stats.experience': 'Years of Experience',
    'home.stats.formations': 'Training Programs Delivered',
    'home.services.badge': 'Our Services',
    'home.services.title': 'Discover our cutting-edge services',
    'home.services.subtitle': 'Discover our complete range of technical services and professional training programs',
    'home.why.title': 'Why Choose EXFORM?',
    'home.why.subtitle': 'With over 15 years of experience, EXFORM has established itself as the reference partner for your technical expertise and professional training needs.',
    'home.why.point1': 'Certified and recognized technical expertise',
    'home.why.point2': 'Training adapted to market needs',
    'home.why.point3': 'Laboratory equipped to international standards',
    'home.why.point4': 'Personalized project support',
    'home.partners.title': 'Our Trusted Partners',
    'home.partners.subtitle': 'We collaborate with industry leaders to offer you the best solutions',
    'home.faq.title': 'Frequently Asked Questions',
    'home.faq.subtitle': 'Find quick answers to your questions',
    'home.faq.more': 'Have more questions?',
    'home.faq.q1': 'What are your accreditations and certifications?',
    'home.faq.a1': 'EXFORM holds ISO 9001 and ISO 17025 certifications for our laboratories. We are also COFRAC accredited and recognized by international standardization bodies.',
    'home.faq.q2': 'How long do your training programs last?',
    'home.faq.a2': 'Our training programs range from 2 days to several weeks depending on the program. We also offer customized training adapted to your specific needs.',
    'home.faq.q3': 'Do you provide post-training support?',
    'home.faq.a3': 'Yes, we offer personalized follow-up after each training including access to our online resources and technical support for 3 months.',
    'home.faq.q4': 'What types of analyses do you perform in your laboratory?',
    'home.faq.a4': 'Our laboratory performs physico-chemical, microbiological, environmental and construction materials analyses according to international standards.',
    'home.faq.q5': 'How can I get a quote for your services?',
    'home.faq.a5': 'You can request a free quote via our contact form or by calling us directly. We respond within 24 hours.',
    'home.cta.title': 'Ready to Develop Your Skills?',
    'home.cta.subtitle': 'Contact us today to discuss your training and technical expertise needs',
    'home.cta.contact': 'Contact us',
    'home.cta.trainings': 'View our training',

    // Registration
    'register.title': 'Training Registration',
    'register.subtitle': 'Please fill in the form to register for a training program',
    'register.submit': 'Register',
    'register.step1.title': 'Personal Information',
    'register.step1.label': 'Personal information',
    'register.step2.title': 'Professional Information',
    'register.step2.label': 'Professional information',
    'register.step3.title': 'Training Selection',
    'register.step3.label': 'Training selection',
    'register.firstName': 'First Name',
    'register.firstName.placeholder': 'Your first name',
    'register.lastName': 'Last Name',
    'register.lastName.placeholder': 'Your last name',
    'register.email': 'Email',
    'register.email.placeholder': 'your.email@example.com',
    'register.phone': 'Phone',
    'register.phone.placeholder': '+225 07 00 00 00 00',
    'register.company': 'Company',
    'register.company.placeholder': 'Your company name',
    'register.position': 'Position',
    'register.position.placeholder': 'Your current position',
    'register.experience': 'Years of Experience',
    'register.experience.placeholder': 'Select your experience level',
    'register.experience.0-2': '0-2 years',
    'register.experience.3-5': '3-5 years',
    'register.experience.6-10': '6-10 years',
    'register.experience.10+': 'More than 10 years',
    'register.training': 'Preferred Training',
    'register.training.placeholder': 'Choose your training',
    'register.startDate': 'Preferred Start Date',
    'register.motivation': 'Motivation / Goals',
    'register.motivation.placeholder': 'Describe your goals and motivations for this training...',
    'register.characters': 'characters',
    'register.summary': 'Summary',
    'register.fullName': 'Full Name',
    'register.previous': 'Previous',
    'register.next': 'Next',
    'register.backToTraining': 'Back to training',
    'register.submitting': 'Registering...',
    'register.toast.success': 'Registration successful!',
    'register.toast.description': 'We will contact you within 48 hours to confirm your registration.',

    // Thanks
    'thanks.title': 'Thank you!',
    'thanks.message': 'We will contact you shortly',
    'thanks.nextSteps': 'Next Steps',
    'thanks.step1.title': 'Confirmation within 48h',
    'thanks.step1.desc': 'Our team will contact you to confirm your registration and practical arrangements.',
    'thanks.step2.title': 'Training preparation',
    'thanks.step2.desc': 'Receive documents and teaching materials before the training begins.',
    'thanks.step3.title': 'Start of your training',
    'thanks.step3.desc': 'Personalized support throughout your learning journey.',
    'thanks.contactQuestion': 'Any questions? Contact us',
    'thanks.otherTrainings': 'See other trainings',
    'thanks.aboutExform': 'About EXFORM',
    'thanks.aboutExformDesc': 'Discover our history and values',
    'thanks.ourServices': 'Our Services',
    'thanks.ourServicesDesc': 'Explore our full range of services',
    'thanks.contactUs': 'Contact Us',
    'thanks.contactUsDesc': 'All our contact details and location',

    // Footer
    'footer.navigation': 'Navigation',
    'footer.copyright': 'All rights reserved.',
    'footer.legal': 'Legal notice',
    'footer.privacy': 'Privacy policy',

    // Chatbot
    'chatbot.greeting': 'Hello! I\'m EXFORM\'s virtual assistant. How can I help you today?',
    'chatbot.online': 'Online',
    'chatbot.placeholder': 'Type your message...',
    'chatbot.services': 'EXFORM offers three main services: Physico-chemical analysis laboratory, Qualifying continuing education, and Construction & industrial equipment. Would you like to know more about any of these services?',
    'chatbot.laboratory': 'Our laboratory provides comprehensive analyses according to ISO and HACCP standards. We cover water, air, dust, sound and environmental analyses.',
    'chatbot.training': 'Our training includes vibratory analysis, hydraulics, sealing systems, ammonia-related risks, and much more. Would you like to register?',
    'chatbot.contact': 'You can contact us in Yopougon opposite the CHU, or use our online contact form. Our team will respond quickly.',
    'chatbot.default': 'Thank you for your question. For detailed information, I invite you to contact us directly or consult our service pages.',

    // WhatsApp
    'whatsapp.title': 'Contact us on WhatsApp',
    'whatsapp.message': 'Hello, I\'m contacting you from your EXFORM website. I would like to have information about your services.',

    // Common
    'common.learnMore': 'Learn more',
    'common.backHome': 'Back to home',
    'common.servicesBadge': 'Our Services',
    'common.contact': 'Contact',
    'common.contactUs': 'Contact us',

    // SEO
    'seo.home.title': 'EXFORM - Technical Expertise & Professional Training | Ivory Coast',
    'seo.home.description': 'EXFORM, leader in technical expertise and professional training in Ivory Coast. ISO certified physico-chemical analysis laboratory, qualifying continuing education.',
    'seo.about.title': 'About EXFORM | Our Story and Values',
    'seo.about.description': 'Discover EXFORM\'s story, our mission, vision and values. Over 15 years of experience in technical expertise and training in Ivory Coast.',
    'seo.services.title': 'Our Services | Laboratory, Construction, Industrial Maintenance - EXFORM',
    'seo.services.description': 'Discover our services: physico-chemical analysis laboratory, construction and industrial equipment, burner maintenance. Complete technical solutions.',
    'seo.laboratory.title': 'Physico-Chemical Analysis Laboratory | EXFORM Ivory Coast',
    'seo.laboratory.description': 'ISO and HACCP certified laboratory. Physico-chemical analyses, food quality control, high-precision environmental analyses.',
    'seo.training.title': 'Certified Professional Training | EXFORM',
    'seo.training.description': 'Qualifying continuing education: vibration analysis, hydraulics, ammonia, management. Expert trainers and recognized certifications.',
    'seo.contact.title': 'Contact EXFORM | Free Quote and Information',
    'seo.contact.description': 'Contact EXFORM in Abidjan, Yopougon. Request a free quote for our laboratory, training and industrial maintenance services.',
    'seo.register.title': 'Training Registration | EXFORM',
    'seo.register.description': 'Register for our certified professional training. Develop your skills with EXFORM experts.',
    'seo.thanks.title': 'Thank you for your registration | EXFORM',
    'seo.thanks.description': 'Your registration has been recorded. Our team will contact you within 48 hours to confirm the details.',
    'seo.notfound.title': 'Page Not Found | EXFORM',
    'seo.notfound.description': 'The page you are looking for does not exist. Return to home to explore our services.',

    // 404 Page
    'notfound.title': 'Page not found',
    'notfound.description': 'Sorry, the page you are looking for does not exist or has been moved. Check the URL or return to the homepage.',
    'notfound.home': 'Back to home',
    'notfound.contact': 'Contact us',
    'notfound.suggestions': 'Pages that might interest you:',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
