import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.about': 'Présentation',
    'nav.services': 'Services',
    'nav.laboratory': 'Laboratoire',
    'nav.training': 'Formations',
    'nav.contact': 'Contact',

    // Hero Section
    'hero.title': 'Expertise Technique & Formation aux Métiers',
    'hero.subtitle': 'Excellence, Innovation et Professionnalisme au service de votre développement',
    'hero.cta': 'Découvrir nos services',

    // About
    'about.title': 'À propos d\'EXFORM',
    'about.subtitle': 'Notre mission, nos valeurs, notre vision',
    'about.cta': 'Contactez-nous',
    'about.history.badge': 'Notre Parcours',
    'about.history.title': 'Notre Histoire',
    'about.history.p1': 'Fondée avec la vision de transformer le paysage de la formation technique et de l\'expertise industrielle en Côte d\'Ivoire, EXFORM s\'est rapidement imposée comme un acteur incontournable du secteur.',
    'about.history.p2': 'Depuis nos débuts, nous avons formé plus de 500 professionnels et accompagné des centaines d\'entreprises dans leur développement. Notre laboratoire d\'analyse physico-chimique est reconnu pour sa précision et sa conformité aux normes internationales.',
    'about.history.p3': 'Aujourd\'hui, EXFORM continue d\'évoluer pour répondre aux défis technologiques et industriels de demain, tout en maintenant notre engagement envers l\'excellence et l\'innovation.',
    'about.stats.experience': 'Années d\'Expérience',
    'about.stats.professionals': 'Professionnels Formés',
    'about.stats.partners': 'Entreprises Partenaires',
    'about.stats.trainings': 'Formations Disponibles',
    'about.mission.title': 'Notre Mission',
    'about.mission.text': 'Fournir des services d\'expertise technique et de formation de classe mondiale, en accompagnant nos clients dans leur développement professionnel et industriel. Nous nous engageons à délivrer des solutions innovantes et adaptées aux défis technologiques contemporains.',
    'about.vision.title': 'Notre Vision',
    'about.vision.text': 'Devenir le leader régional de l\'expertise technique et de la formation professionnelle, reconnu pour notre excellence, notre innovation et notre impact positif sur le développement des compétences industrielles en Afrique de l\'Ouest.',
    'about.values.title': 'Nos Valeurs',
    'about.values.subtitle': 'Les principes qui guident notre action quotidienne et définissent notre identité',
    'about.values.excellence': 'Excellence',
    'about.values.excellence.desc': 'Nous visons l\'excellence dans chaque service que nous proposons, avec des standards de qualité élevés.',
    'about.values.innovation': 'Innovation',
    'about.values.innovation.desc': 'Nous intégrons les dernières technologies et méthodes pour rester à la pointe de notre domaine.',
    'about.values.partnership': 'Partenariat',
    'about.values.partnership.desc': 'Nous construisons des relations durables basées sur la confiance et la collaboration.',
    'about.values.commitment': 'Engagement',
    'about.values.commitment.desc': 'Nous nous engageons pleinement dans la réussite de nos clients et partenaires.',
    'about.team.title': 'Notre Équipe',
    'about.team.subtitle': 'Une équipe d\'experts passionnés et expérimentés, dédiée à votre succès',
    'about.team.multidisciplinary': 'Équipe Multidisciplinaire',
    'about.team.multidisciplinary.desc': 'Notre équipe réunit des ingénieurs, des formateurs certifiés, des techniciens spécialisés et des consultants expérimentés. Chaque membre apporte son expertise unique pour vous offrir des services de la plus haute qualité.',
    'about.cta.title': 'Travaillons Ensemble',
    'about.cta.subtitle': 'Découvrez comment EXFORM peut vous accompagner dans vos projets',

    // Services
    'services.title': 'Découvrez nos services de pointe',
    'services.subtitle': 'Des solutions techniques innovantes et des formations de qualité pour accompagner votre développement',
    'services.badge': 'Services Techniques Avancés',
    'services.laboratory': 'Laboratoire d\'analyse physico-chimique',
    'services.laboratory.desc': 'Analyses physico-chimiques complètes selon les normes ISO et HACCP. Notre laboratoire moderne offre des services de contrôle qualité et de certification pour tous secteurs d\'activité.',
    'services.construction': 'BTP et équipements industriels',
    'services.construction.desc': 'Solutions complètes pour vos projets BTP et équipements industriels. De la conception à la réalisation, nous vous accompagnons avec expertise et professionnalisme.',
    'services.training': 'Formation continue qualifiante',
    'services.training.desc': 'Formations continues qualifiantes adaptées aux besoins du marché. Développez les compétences de vos équipes avec nos programmes certifiés et personnalisés.',
    'services.maintenance': 'Pluri-mécanique et maintenance industrielle',
    'services.maintenance.desc': 'Services de maintenance préventive et corrective pour vos équipements industriels. Optimisez la performance et la durée de vie de vos installations.',
    'services.burner.title': 'Maintenance des Brûleurs Industriels',
    'services.burner.subtitle': 'Installation, contrôle annuel, maintenance des brûleurs gaz ou fuel des marques WEISHAUPT et SAAKE installés sur des chaudières ou des torréfacteurs',
    'services.burner.installation': 'Installation',
    'services.burner.installation.desc': 'Installation professionnelle de brûleurs industriels',
    'services.burner.control': 'Contrôle Annuel',
    'services.burner.control.desc': 'Contrôles périodiques et certifications',
    'services.burner.maintenance': 'Maintenance',
    'services.burner.maintenance.desc': 'Maintenance préventive et corrective',
    'services.additional.title': 'Services Complémentaires',
    'services.additional.subtitle': 'Une gamme étendue de services pour répondre à tous vos besoins techniques et industriels',
    'services.additional.1': 'Études et projets industriels (PGE-A et EIES)',
    'services.additional.2': 'Conseil en organisation industrielle',
    'services.additional.3': 'Audit technique et énergétique',
    'services.additional.4': 'Accompagnement certification qualité',
    'services.additional.5': 'Formation en sécurité industrielle',
    'services.additional.6': 'Support technique spécialisé',
    'services.process.title': 'Notre Processus',
    'services.process.subtitle': 'Une approche structurée pour garantir la qualité et la satisfaction de nos clients',
    'services.process.step1': 'Analyse des Besoins',
    'services.process.step1.desc': 'Évaluation complète de vos besoins et objectifs',
    'services.process.step2': 'Proposition Solution',
    'services.process.step2.desc': 'Développement d\'une solution personnalisée',
    'services.process.step3': 'Mise en Œuvre',
    'services.process.step3.desc': 'Réalisation avec suivi qualité rigoureux',
    'services.process.step4': 'Suivi & Support',
    'services.process.step4.desc': 'Accompagnement continu et support technique',
    'services.cta.title': 'Prêt à Commencer Votre Projet ?',
    'services.cta.subtitle': 'Contactez nos experts pour une consultation personnalisée et un devis gratuit',
    'services.features.iso': 'Analyses conformes ISO 9001',
    'services.features.haccp': 'Certifications HACCP',
    'services.features.food': 'Contrôle qualité alimentaire',
    'services.features.env': 'Analyses environnementales',
    'services.features.studies': 'Études et conception',
    'services.features.btp': 'Réalisation de projets BTP',
    'services.features.install': 'Installation d\'équipements',
    'services.features.maintenance': 'Maintenance industrielle',
    'services.features.certified': 'Formations certifiantes',
    'services.features.custom': 'Programmes sur mesure',
    'services.features.experts': 'Formateurs experts',
    'services.features.followup': 'Suivi post-formation',
    'services.features.preventive': 'Maintenance préventive',
    'services.features.emergency': 'Dépannage d\'urgence',
    'services.features.performance': 'Optimisation performance',
    'services.features.contracts': 'Contrats de maintenance',

    // Training
    'training.title': 'Nos Formations',
    'training.subtitle': 'Développez vos compétences techniques avec nos formations certifiantes dispensées par des experts',
    'training.badge': 'Formation Continue',
    'training.register': 'Je m\'inscris',
    'training.vibration': 'Analyse vibratoire',
    'training.vibration.desc': 'Formation complète sur l\'analyse vibratoire pour le diagnostic et la maintenance prédictive des équipements industriels.',
    'training.hydraulics': 'Hydraulique',
    'training.hydraulics.desc': 'Maîtrisez les systèmes hydrauliques industriels, de la conception à la maintenance en passant par la réparation.',
    'training.ammonia': 'Ammoniac',
    'training.ammonia.desc': 'Formation spécialisée sur les risques liés à l\'ammoniac et les mesures de sécurité dans l\'industrie frigorifique.',
    'training.filtration': 'Filtration air',
    'training.filtration.desc': 'Apprenez les techniques de filtration d\'air pour l\'industrie et les environnements contrôlés.',
    'training.pressure': 'Pression/Autoclave',
    'training.pressure.desc': 'Formation sur les équipements sous pression et autoclaves, réglementation et sécurité.',
    'training.management': 'Management',
    'training.management.desc': 'Développez vos compétences managériales pour diriger efficacement vos équipes techniques.',
    'training.overview.title': 'Formation Continue Qualifiante',
    'training.overview.p1': 'EXFORM propose un catalogue complet de formations techniques adaptées aux besoins du marché industriel. Nos programmes sont conçus pour développer vos compétences et vous maintenir à la pointe des technologies.',
    'training.overview.p2': 'Que vous soyez débutant ou expert, nos formations modulaires vous permettent d\'évoluer à votre rythme avec un accompagnement personnalisé de nos formateurs certifiés.',
    'training.overview.p3': 'Chaque formation débouche sur une certification reconnue par l\'industrie, valorisant ainsi vos nouvelles compétences auprès de vos employeurs ou clients.',
    'training.programs.title': 'Nos Programmes de Formation',
    'training.programs.subtitle': 'Choisissez parmi notre catalogue de formations techniques spécialisées',
    'training.why.title': 'Pourquoi Choisir Nos Formations ?',
    'training.why.subtitle': 'Les avantages qui font la différence dans votre parcours de formation',
    'training.why.experts': 'Formateurs Experts',
    'training.why.experts.desc': 'Nos formateurs sont des professionnels expérimentés avec une expertise terrain reconnue.',
    'training.why.certified': 'Certifications Reconnues',
    'training.why.certified.desc': 'Obtenez des certifications reconnues par l\'industrie et valorisez vos compétences.',
    'training.why.flexibility': 'Flexibilité Horaire',
    'training.why.flexibility.desc': 'Formations adaptées à votre planning avec des sessions en journée ou en soirée.',
    'training.why.followup': 'Suivi Personnalisé',
    'training.why.followup.desc': 'Un accompagnement individualisé pour garantir votre progression et réussite.',
    'training.process.title': 'Processus de Formation',
    'training.process.subtitle': 'Un parcours structuré pour maximiser votre apprentissage',
    'training.process.step1': 'Inscription',
    'training.process.step1.desc': 'Choisissez votre formation et inscrivez-vous en ligne',
    'training.process.step2': 'Évaluation',
    'training.process.step2.desc': 'Évaluation de votre niveau pour adapter le programme',
    'training.process.step3': 'Formation',
    'training.process.step3.desc': 'Sessions théoriques et pratiques avec nos experts',
    'training.process.step4': 'Certification',
    'training.process.step4.desc': 'Examen final et remise de votre certification',
    'training.cta.title': 'Investissez dans Votre Avenir',
    'training.cta.subtitle': 'Rejoignez les milliers de professionnels qui ont développé leurs compétences avec EXFORM',
    'training.cta.info': 'Demander des informations',
    'training.level.intermediate': 'Intermédiaire',
    'training.level.all': 'Tous niveaux',
    'training.level.specialized': 'Spécialisé',
    'training.level.technical': 'Technique',
    'training.level.advanced': 'Avancé',
    'training.level.management': 'Management',
    'training.duration.days': 'jours',

    // Laboratory
    'lab.title': 'Laboratoire d\'Analyse',
    'lab.subtitle': 'Expertise physico-chimique, ISO, HACCP, analyses complètes',
    'lab.cta': 'Contactez-nous pour vos analyses',
    'lab.badge': 'Laboratoire d\'Expertise',
    'lab.hero.title': 'Laboratoire d\'Analyse Physico-Chimique',
    'lab.hero.subtitle': 'Analyses de précision conformes aux normes internationales ISO et HACCP pour tous vos besoins industriels',
    'lab.overview.title': 'Excellence Analytique',
    'lab.overview.p1': 'Notre laboratoire d\'analyse physico-chimique est équipé des technologies les plus avancées pour répondre à vos besoins en contrôle qualité et certification.',
    'lab.overview.p2': 'Nous proposons des analyses complètes et précises, conformes aux normes internationales, pour les secteurs alimentaire, environnemental, industriel et pharmaceutique.',
    'lab.overview.p3': 'Notre équipe de chimistes et techniciens qualifiés garantit des résultats fiables et un accompagnement personnalisé pour l\'interprétation de vos analyses.',
    'lab.services.title': 'Nos Services d\'Analyse',
    'lab.services.subtitle': 'Une gamme complète d\'analyses pour répondre à tous vos besoins',
    'lab.equipment.title': 'Équipements de Pointe',
    'lab.equipment.subtitle': 'Des technologies avancées pour des analyses précises et fiables',
    'lab.certifications.title': 'Nos Certifications',
    'lab.certifications.subtitle': 'Des accréditations reconnues garantissant la qualité de nos analyses',
    'lab.process.title': 'Processus d\'Analyse',
    'lab.process.subtitle': 'Un processus rigoureux pour des résultats fiables',
    'lab.process.step1': 'Réception',
    'lab.process.step1.desc': 'Réception et enregistrement de vos échantillons',
    'lab.process.step2': 'Préparation',
    'lab.process.step2.desc': 'Préparation selon les protocoles normalisés',
    'lab.process.step3': 'Analyse',
    'lab.process.step3.desc': 'Analyses avec équipements certifiés',
    'lab.process.step4': 'Validation',
    'lab.process.step4.desc': 'Validation et contrôle qualité des résultats',
    'lab.process.step5': 'Rapport',
    'lab.process.step5.desc': 'Remise du rapport d\'analyse détaillé',
    'lab.cta.title': 'Besoin d\'une Analyse ?',
    'lab.cta.subtitle': 'Contactez notre équipe pour discuter de vos besoins en analyse et obtenir un devis personnalisé',
    'lab.cta.button': 'Demander un Devis',

    // Contact
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Nous sommes à votre écoute pour répondre à toutes vos questions et vous accompagner dans vos projets',
    'contact.address': 'Yopougon – en face du CHU',
    'contact.form.title': 'Envoyez-nous un Message',
    'contact.form.name': 'Nom complet',
    'contact.form.name.placeholder': 'Votre nom complet',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'votre.email@exemple.com',
    'contact.form.phone': 'Téléphone',
    'contact.form.phone.placeholder': 'Votre numéro de téléphone',
    'contact.form.subject': 'Sujet',
    'contact.form.subject.placeholder': 'Sujet de votre message',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Décrivez votre besoin ou votre question...',
    'contact.form.send': 'Envoyer le message',
    'contact.form.sending': 'Envoi en cours...',
    'contact.info.title': 'Nos Coordonnées',
    'contact.info.address': 'Adresse',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Téléphone',
    'contact.info.hours': 'Horaires',
    'contact.hours.weekday': 'Lundi - Vendredi: 8h - 18h',
    'contact.hours.saturday': 'Samedi: 8h - 13h',
    'contact.map.title': 'Notre Localisation',
    'contact.map.subtitle': 'Retrouvez-nous facilement à Yopougon, en face du CHU',
    'contact.map.placeholder': 'Intégration Google Maps',
    'contact.map.coming': 'Carte interactive disponible prochainement',
    'contact.faq.title': 'Questions Fréquentes',
    'contact.faq.q1': 'Quels sont vos délais de réponse ?',
    'contact.faq.a1': 'Nous nous engageons à répondre à toute demande dans les 24h ouvrées.',
    'contact.faq.q2': 'Proposez-vous des formations sur site ?',
    'contact.faq.a2': 'Oui, nous pouvons organiser des formations directement dans vos locaux selon vos besoins.',
    'contact.faq.q3': 'Comment obtenir un devis pour une analyse ?',
    'contact.faq.a3': 'Contactez-nous avec les détails de votre besoin, nous vous fournirons un devis gratuit sous 48h.',
    'contact.quick.training': 'S\'inscrire à une formation',
    'contact.quick.analysis': 'Demander une analyse',
    'contact.toast.success': 'Message envoyé !',
    'contact.toast.description': 'Nous vous contacterons très bientôt.',

    // Home
    'home.stats.clients': 'Clients Satisfaits',
    'home.stats.experience': 'Années d\'Expérience',
    'home.stats.formations': 'Formations Dispensées',
    'home.services.badge': 'Nos Services',
    'home.services.title': 'Découvrez nos services de pointe',
    'home.services.subtitle': 'Découvrez notre gamme complète de services techniques et de formations professionnelles',
    'home.why.title': 'Pourquoi Choisir EXFORM ?',
    'home.why.subtitle': 'Avec plus de 15 ans d\'expérience, EXFORM s\'impose comme le partenaire de référence pour vos besoins en expertise technique et formation professionnelle.',
    'home.why.point1': 'Expertise technique certifiée et reconnue',
    'home.why.point2': 'Formations adaptées aux besoins du marché',
    'home.why.point3': 'Laboratoire équipé aux normes internationales',
    'home.why.point4': 'Accompagnement personnalisé de vos projets',
    'home.partners.title': 'Nos Partenaires de Confiance',
    'home.partners.subtitle': 'Nous collaborons avec les leaders de l\'industrie pour vous offrir les meilleures solutions',
    'home.faq.title': 'Questions Fréquemment Posées',
    'home.faq.subtitle': 'Trouvez rapidement des réponses à vos questions',
    'home.faq.more': 'Vous avez d\'autres questions ?',
    'home.faq.q1': 'Quelles sont vos accréditations et certifications ?',
    'home.faq.a1': 'EXFORM dispose des certifications ISO 9001 et ISO 17025 pour nos laboratoires. Nous sommes également accrédités COFRAC et reconnus par les organismes internationaux de normalisation.',
    'home.faq.q2': 'Combien de temps durent vos formations ?',
    'home.faq.a2': 'Nos formations varient de 2 jours à plusieurs semaines selon le programme. Nous proposons également des formations sur mesure adaptées à vos besoins spécifiques.',
    'home.faq.q3': 'Proposez-vous un accompagnement post-formation ?',
    'home.faq.a3': 'Oui, nous offrons un suivi personnalisé après chaque formation incluant un accès à nos ressources en ligne et un support technique pendant 3 mois.',
    'home.faq.q4': 'Quels types d\'analyses effectuez-vous dans votre laboratoire ?',
    'home.faq.a4': 'Notre laboratoire réalise des analyses physico-chimiques, microbiologiques, environnementales et des matériaux de construction selon les normes internationales.',
    'home.faq.q5': 'Comment obtenir un devis pour vos services ?',
    'home.faq.a5': 'Vous pouvez demander un devis gratuit via notre formulaire de contact ou en nous appelant directement. Nous vous répondons sous 24h.',
    'home.cta.title': 'Prêt à Développer Vos Compétences ?',
    'home.cta.subtitle': 'Contactez-nous dès aujourd\'hui pour discuter de vos besoins en formation et expertise technique',
    'home.cta.contact': 'Nous contacter',
    'home.cta.trainings': 'Voir nos formations',

    // Registration
    'register.title': 'Inscription à une formation',
    'register.subtitle': 'Bonjour, veuillez remplir le formulaire pour vous inscrire à une formation',
    'register.submit': 'S\'inscrire',

    // Thanks
    'thanks.title': 'Merci !',
    'thanks.message': 'Nous vous contacterons très bientôt',

    // Common
    'common.learn_more': 'En savoir plus',
    'common.back_home': 'Retour à l\'accueil',
    'common.services_badge': 'Nos Services',
    'common.contact': 'Contact',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.laboratory': 'Laboratory',
    'nav.training': 'Training',
    'nav.contact': 'Contact',

    // Hero Section
    'hero.title': 'Technical Expertise & Professional Training',
    'hero.subtitle': 'Excellence, Innovation and Professionalism serving your development',
    'hero.cta': 'Explore our Services',

    // About
    'about.title': 'About EXFORM',
    'about.subtitle': 'Our mission, our values, our vision',
    'about.cta': 'Contact us',
    'about.history.badge': 'Our Journey',
    'about.history.title': 'Our Story',
    'about.history.p1': 'Founded with the vision of transforming the technical training and industrial expertise landscape in Ivory Coast, EXFORM has quickly established itself as a key player in the sector.',
    'about.history.p2': 'Since our beginnings, we have trained over 500 professionals and supported hundreds of companies in their development. Our physico-chemical analysis laboratory is recognized for its precision and compliance with international standards.',
    'about.history.p3': 'Today, EXFORM continues to evolve to meet the technological and industrial challenges of tomorrow, while maintaining our commitment to excellence and innovation.',
    'about.stats.experience': 'Years of Experience',
    'about.stats.professionals': 'Professionals Trained',
    'about.stats.partners': 'Partner Companies',
    'about.stats.trainings': 'Available Training Programs',
    'about.mission.title': 'Our Mission',
    'about.mission.text': 'Provide world-class technical expertise and training services, supporting our clients in their professional and industrial development. We are committed to delivering innovative solutions adapted to contemporary technological challenges.',
    'about.vision.title': 'Our Vision',
    'about.vision.text': 'Become the regional leader in technical expertise and professional training, recognized for our excellence, innovation and positive impact on industrial skills development in West Africa.',
    'about.values.title': 'Our Values',
    'about.values.subtitle': 'The principles that guide our daily action and define our identity',
    'about.values.excellence': 'Excellence',
    'about.values.excellence.desc': 'We strive for excellence in every service we offer, with high quality standards.',
    'about.values.innovation': 'Innovation',
    'about.values.innovation.desc': 'We integrate the latest technologies and methods to stay at the forefront of our field.',
    'about.values.partnership': 'Partnership',
    'about.values.partnership.desc': 'We build lasting relationships based on trust and collaboration.',
    'about.values.commitment': 'Commitment',
    'about.values.commitment.desc': 'We are fully committed to the success of our clients and partners.',
    'about.team.title': 'Our Team',
    'about.team.subtitle': 'A team of passionate and experienced experts, dedicated to your success',
    'about.team.multidisciplinary': 'Multidisciplinary Team',
    'about.team.multidisciplinary.desc': 'Our team brings together engineers, certified trainers, specialized technicians and experienced consultants. Each member brings their unique expertise to offer you the highest quality services.',
    'about.cta.title': 'Let\'s Work Together',
    'about.cta.subtitle': 'Discover how EXFORM can support you in your projects',

    // Services
    'services.title': 'Discover our cutting-edge services',
    'services.subtitle': 'Innovative technical solutions and quality training to support your development',
    'services.badge': 'Advanced Technical Services',
    'services.laboratory': 'Physico-chemical Analysis Laboratory',
    'services.laboratory.desc': 'Complete physico-chemical analyses according to ISO and HACCP standards. Our modern laboratory offers quality control and certification services for all business sectors.',
    'services.construction': 'Construction & Industrial Equipment',
    'services.construction.desc': 'Complete solutions for your construction and industrial equipment projects. From design to implementation, we support you with expertise and professionalism.',
    'services.training': 'Continuous Professional Training',
    'services.training.desc': 'Continuous professional training adapted to market needs. Develop your teams\' skills with our certified and personalized programs.',
    'services.maintenance': 'Multi-mechanics & Industrial Maintenance',
    'services.maintenance.desc': 'Preventive and corrective maintenance services for your industrial equipment. Optimize the performance and lifespan of your installations.',
    'services.burner.title': 'Industrial Burner Maintenance',
    'services.burner.subtitle': 'Installation, annual inspection, maintenance of gas or fuel burners from WEISHAUPT and SAAKE brands installed on boilers or roasters',
    'services.burner.installation': 'Installation',
    'services.burner.installation.desc': 'Professional installation of industrial burners',
    'services.burner.control': 'Annual Inspection',
    'services.burner.control.desc': 'Periodic inspections and certifications',
    'services.burner.maintenance': 'Maintenance',
    'services.burner.maintenance.desc': 'Preventive and corrective maintenance',
    'services.additional.title': 'Additional Services',
    'services.additional.subtitle': 'An extended range of services to meet all your technical and industrial needs',
    'services.additional.1': 'Industrial studies and projects (PGE-A and EIES)',
    'services.additional.2': 'Industrial organization consulting',
    'services.additional.3': 'Technical and energy audit',
    'services.additional.4': 'Quality certification support',
    'services.additional.5': 'Industrial safety training',
    'services.additional.6': 'Specialized technical support',
    'services.process.title': 'Our Process',
    'services.process.subtitle': 'A structured approach to ensure quality and customer satisfaction',
    'services.process.step1': 'Needs Analysis',
    'services.process.step1.desc': 'Complete assessment of your needs and objectives',
    'services.process.step2': 'Solution Proposal',
    'services.process.step2.desc': 'Development of a customized solution',
    'services.process.step3': 'Implementation',
    'services.process.step3.desc': 'Execution with rigorous quality monitoring',
    'services.process.step4': 'Follow-up & Support',
    'services.process.step4.desc': 'Ongoing support and technical assistance',
    'services.cta.title': 'Ready to Start Your Project?',
    'services.cta.subtitle': 'Contact our experts for a personalized consultation and free quote',
    'services.features.iso': 'ISO 9001 compliant analyses',
    'services.features.haccp': 'HACCP certifications',
    'services.features.food': 'Food quality control',
    'services.features.env': 'Environmental analyses',
    'services.features.studies': 'Studies and design',
    'services.features.btp': 'Construction project execution',
    'services.features.install': 'Equipment installation',
    'services.features.maintenance': 'Industrial maintenance',
    'services.features.certified': 'Certified training',
    'services.features.custom': 'Custom programs',
    'services.features.experts': 'Expert trainers',
    'services.features.followup': 'Post-training follow-up',
    'services.features.preventive': 'Preventive maintenance',
    'services.features.emergency': 'Emergency repair',
    'services.features.performance': 'Performance optimization',
    'services.features.contracts': 'Maintenance contracts',

    // Training
    'training.title': 'Our Training Programs',
    'training.subtitle': 'Develop your technical skills with our certified training delivered by experts',
    'training.badge': 'Continuous Training',
    'training.register': 'Register now',
    'training.vibration': 'Vibration Analysis',
    'training.vibration.desc': 'Complete training on vibration analysis for diagnosis and predictive maintenance of industrial equipment.',
    'training.hydraulics': 'Hydraulics',
    'training.hydraulics.desc': 'Master industrial hydraulic systems, from design to maintenance and repair.',
    'training.ammonia': 'Ammonia Safety',
    'training.ammonia.desc': 'Specialized training on ammonia-related risks and safety measures in the refrigeration industry.',
    'training.filtration': 'Air Filtration',
    'training.filtration.desc': 'Learn air filtration techniques for industry and controlled environments.',
    'training.pressure': 'Pressure/Autoclave',
    'training.pressure.desc': 'Training on pressure equipment and autoclaves, regulations and safety.',
    'training.management': 'Management',
    'training.management.desc': 'Develop your management skills to effectively lead your technical teams.',
    'training.overview.title': 'Continuous Professional Training',
    'training.overview.p1': 'EXFORM offers a complete catalog of technical training adapted to industrial market needs. Our programs are designed to develop your skills and keep you at the cutting edge of technology.',
    'training.overview.p2': 'Whether you are a beginner or an expert, our modular training programs allow you to progress at your own pace with personalized support from our certified trainers.',
    'training.overview.p3': 'Each training leads to an industry-recognized certification, thus enhancing your new skills with your employers or clients.',
    'training.programs.title': 'Our Training Programs',
    'training.programs.subtitle': 'Choose from our catalog of specialized technical training',
    'training.why.title': 'Why Choose Our Training?',
    'training.why.subtitle': 'The advantages that make a difference in your training journey',
    'training.why.experts': 'Expert Trainers',
    'training.why.experts.desc': 'Our trainers are experienced professionals with recognized field expertise.',
    'training.why.certified': 'Recognized Certifications',
    'training.why.certified.desc': 'Obtain industry-recognized certifications and enhance your skills.',
    'training.why.flexibility': 'Schedule Flexibility',
    'training.why.flexibility.desc': 'Training adapted to your schedule with day or evening sessions.',
    'training.why.followup': 'Personalized Follow-up',
    'training.why.followup.desc': 'Individual support to ensure your progress and success.',
    'training.process.title': 'Training Process',
    'training.process.subtitle': 'A structured path to maximize your learning',
    'training.process.step1': 'Registration',
    'training.process.step1.desc': 'Choose your training and register online',
    'training.process.step2': 'Assessment',
    'training.process.step2.desc': 'Assessment of your level to adapt the program',
    'training.process.step3': 'Training',
    'training.process.step3.desc': 'Theoretical and practical sessions with our experts',
    'training.process.step4': 'Certification',
    'training.process.step4.desc': 'Final exam and delivery of your certification',
    'training.cta.title': 'Invest in Your Future',
    'training.cta.subtitle': 'Join the thousands of professionals who have developed their skills with EXFORM',
    'training.cta.info': 'Request information',
    'training.level.intermediate': 'Intermediate',
    'training.level.all': 'All levels',
    'training.level.specialized': 'Specialized',
    'training.level.technical': 'Technical',
    'training.level.advanced': 'Advanced',
    'training.level.management': 'Management',
    'training.duration.days': 'days',

    // Laboratory
    'lab.title': 'Analysis Laboratory',
    'lab.subtitle': 'Physico-chemical expertise, ISO, HACCP, comprehensive analysis',
    'lab.cta': 'Contact us for your analyses',
    'lab.badge': 'Expertise Laboratory',
    'lab.hero.title': 'Physico-Chemical Analysis Laboratory',
    'lab.hero.subtitle': 'Precision analyses conforming to international ISO and HACCP standards for all your industrial needs',
    'lab.overview.title': 'Analytical Excellence',
    'lab.overview.p1': 'Our physico-chemical analysis laboratory is equipped with the most advanced technologies to meet your quality control and certification needs.',
    'lab.overview.p2': 'We offer complete and precise analyses, conforming to international standards, for the food, environmental, industrial and pharmaceutical sectors.',
    'lab.overview.p3': 'Our team of qualified chemists and technicians guarantees reliable results and personalized support for the interpretation of your analyses.',
    'lab.services.title': 'Our Analysis Services',
    'lab.services.subtitle': 'A complete range of analyses to meet all your needs',
    'lab.equipment.title': 'State-of-the-Art Equipment',
    'lab.equipment.subtitle': 'Advanced technologies for precise and reliable analyses',
    'lab.certifications.title': 'Our Certifications',
    'lab.certifications.subtitle': 'Recognized accreditations guaranteeing the quality of our analyses',
    'lab.process.title': 'Analysis Process',
    'lab.process.subtitle': 'A rigorous process for reliable results',
    'lab.process.step1': 'Reception',
    'lab.process.step1.desc': 'Reception and registration of your samples',
    'lab.process.step2': 'Preparation',
    'lab.process.step2.desc': 'Preparation according to standardized protocols',
    'lab.process.step3': 'Analysis',
    'lab.process.step3.desc': 'Analyses with certified equipment',
    'lab.process.step4': 'Validation',
    'lab.process.step4.desc': 'Validation and quality control of results',
    'lab.process.step5': 'Report',
    'lab.process.step5.desc': 'Delivery of detailed analysis report',
    'lab.cta.title': 'Need an Analysis?',
    'lab.cta.subtitle': 'Contact our team to discuss your analysis needs and get a personalized quote',
    'lab.cta.button': 'Request a Quote',

    // Contact
    'contact.title': 'Contact us',
    'contact.subtitle': 'We are here to listen and answer all your questions and support you in your projects',
    'contact.address': 'Yopougon – opposite CHU Hospital',
    'contact.form.title': 'Send us a Message',
    'contact.form.name': 'Full name',
    'contact.form.name.placeholder': 'Your full name',
    'contact.form.email': 'Email address',
    'contact.form.email.placeholder': 'your.email@example.com',
    'contact.form.phone': 'Phone number',
    'contact.form.phone.placeholder': 'Your phone number',
    'contact.form.subject': 'Subject',
    'contact.form.subject.placeholder': 'Subject of your message',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Describe your needs or ask your question...',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.info.title': 'Our Contact Information',
    'contact.info.address': 'Address',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.hours': 'Business Hours',
    'contact.hours.weekday': 'Monday - Friday: 8am - 6pm',
    'contact.hours.saturday': 'Saturday: 8am - 1pm',
    'contact.map.title': 'Our Location',
    'contact.map.subtitle': 'Find us easily in Yopougon, opposite CHU Hospital',
    'contact.map.placeholder': 'Google Maps Integration',
    'contact.map.coming': 'Interactive map coming soon',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.q1': 'What are your response times?',
    'contact.faq.a1': 'We are committed to responding to any request within 24 working hours.',
    'contact.faq.q2': 'Do you offer on-site training?',
    'contact.faq.a2': 'Yes, we can organize training directly at your premises according to your needs.',
    'contact.faq.q3': 'How to get a quote for analysis?',
    'contact.faq.a3': 'Contact us with the details of your needs, we will provide you with a free quote within 48 hours.',
    'contact.quick.training': 'Register for training',
    'contact.quick.analysis': 'Request analysis',
    'contact.toast.success': 'Message sent!',
    'contact.toast.description': 'We will contact you very soon.',

    // Home
    'home.stats.clients': 'Satisfied Clients',
    'home.stats.experience': 'Years of Experience',
    'home.stats.formations': 'Training Programs Delivered',
    'home.services.badge': 'Our Services',
    'home.services.title': 'Discover our cutting-edge services',
    'home.services.subtitle': 'Discover our complete range of technical services and professional training programs',
    'home.why.title': 'Why Choose EXFORM?',
    'home.why.subtitle': 'With over 15 years of experience, EXFORM has established itself as the reference partner for your technical expertise and professional training needs.',
    'home.why.point1': 'Certified and recognized technical expertise',
    'home.why.point2': 'Training adapted to market needs',
    'home.why.point3': 'Laboratory equipped to international standards',
    'home.why.point4': 'Personalized project support',
    'home.partners.title': 'Our Trusted Partners',
    'home.partners.subtitle': 'We collaborate with industry leaders to offer you the best solutions',
    'home.faq.title': 'Frequently Asked Questions',
    'home.faq.subtitle': 'Find quick answers to your questions',
    'home.faq.more': 'Have more questions?',
    'home.faq.q1': 'What are your accreditations and certifications?',
    'home.faq.a1': 'EXFORM holds ISO 9001 and ISO 17025 certifications for our laboratories. We are also COFRAC accredited and recognized by international standardization bodies.',
    'home.faq.q2': 'How long do your training programs last?',
    'home.faq.a2': 'Our training programs range from 2 days to several weeks depending on the program. We also offer customized training adapted to your specific needs.',
    'home.faq.q3': 'Do you provide post-training support?',
    'home.faq.a3': 'Yes, we offer personalized follow-up after each training including access to our online resources and technical support for 3 months.',
    'home.faq.q4': 'What types of analyses do you perform in your laboratory?',
    'home.faq.a4': 'Our laboratory performs physico-chemical, microbiological, environmental and construction materials analyses according to international standards.',
    'home.faq.q5': 'How can I get a quote for your services?',
    'home.faq.a5': 'You can request a free quote via our contact form or by calling us directly. We respond within 24 hours.',
    'home.cta.title': 'Ready to Develop Your Skills?',
    'home.cta.subtitle': 'Contact us today to discuss your training and technical expertise needs',
    'home.cta.contact': 'Contact us',
    'home.cta.trainings': 'View our training',

    // Registration
    'register.title': 'Training Registration',
    'register.subtitle': 'Please fill in the form to register for a training program',
    'register.submit': 'Register',

    // Thanks
    'thanks.title': 'Thank you!',
    'thanks.message': 'We will contact you shortly',

    // Common
    'common.learn_more': 'Learn more',
    'common.back_home': 'Back to home',
    'common.services_badge': 'Our Services',
    'common.contact': 'Contact',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
